// Code generated by go-swagger; DO NOT EDIT.

package routing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoutingMessageRecipientParams creates a new GetRoutingMessageRecipientParams object
// with the default values initialized.
func NewGetRoutingMessageRecipientParams() *GetRoutingMessageRecipientParams {
	var ()
	return &GetRoutingMessageRecipientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoutingMessageRecipientParamsWithTimeout creates a new GetRoutingMessageRecipientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRoutingMessageRecipientParamsWithTimeout(timeout time.Duration) *GetRoutingMessageRecipientParams {
	var ()
	return &GetRoutingMessageRecipientParams{

		timeout: timeout,
	}
}

// NewGetRoutingMessageRecipientParamsWithContext creates a new GetRoutingMessageRecipientParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRoutingMessageRecipientParamsWithContext(ctx context.Context) *GetRoutingMessageRecipientParams {
	var ()
	return &GetRoutingMessageRecipientParams{

		Context: ctx,
	}
}

// NewGetRoutingMessageRecipientParamsWithHTTPClient creates a new GetRoutingMessageRecipientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRoutingMessageRecipientParamsWithHTTPClient(client *http.Client) *GetRoutingMessageRecipientParams {
	var ()
	return &GetRoutingMessageRecipientParams{
		HTTPClient: client,
	}
}

/*GetRoutingMessageRecipientParams contains all the parameters to send to the API endpoint
for the get routing message recipient operation typically these are written to a http.Request
*/
type GetRoutingMessageRecipientParams struct {

	/*RecipientID
	  Recipient ID

	*/
	RecipientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) WithTimeout(timeout time.Duration) *GetRoutingMessageRecipientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) WithContext(ctx context.Context) *GetRoutingMessageRecipientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) WithHTTPClient(client *http.Client) *GetRoutingMessageRecipientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecipientID adds the recipientID to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) WithRecipientID(recipientID string) *GetRoutingMessageRecipientParams {
	o.SetRecipientID(recipientID)
	return o
}

// SetRecipientID adds the recipientId to the get routing message recipient params
func (o *GetRoutingMessageRecipientParams) SetRecipientID(recipientID string) {
	o.RecipientID = recipientID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoutingMessageRecipientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recipientId
	if err := r.SetPathParam("recipientId", o.RecipientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
