// Code generated by go-swagger; DO NOT EDIT.

package routing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/freman/genesysapi/models"
)

// GetRoutingSkillgroupMembersDivisionsReader is a Reader for the GetRoutingSkillgroupMembersDivisions structure.
type GetRoutingSkillgroupMembersDivisionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoutingSkillgroupMembersDivisionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoutingSkillgroupMembersDivisionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRoutingSkillgroupMembersDivisionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetRoutingSkillgroupMembersDivisionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetRoutingSkillgroupMembersDivisionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRoutingSkillgroupMembersDivisionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewGetRoutingSkillgroupMembersDivisionsRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewGetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewGetRoutingSkillgroupMembersDivisionsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetRoutingSkillgroupMembersDivisionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRoutingSkillgroupMembersDivisionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetRoutingSkillgroupMembersDivisionsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetRoutingSkillgroupMembersDivisionsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRoutingSkillgroupMembersDivisionsOK creates a GetRoutingSkillgroupMembersDivisionsOK with default headers values
func NewGetRoutingSkillgroupMembersDivisionsOK() *GetRoutingSkillgroupMembersDivisionsOK {
	return &GetRoutingSkillgroupMembersDivisionsOK{}
}

/*
GetRoutingSkillgroupMembersDivisionsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetRoutingSkillgroupMembersDivisionsOK struct {
	Payload *models.SkillGroupMemberDivisionList
}

// IsSuccess returns true when this get routing skillgroup members divisions o k response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get routing skillgroup members divisions o k response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions o k response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get routing skillgroup members divisions o k response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions o k response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetRoutingSkillgroupMembersDivisionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsOK  %+v", 200, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsOK  %+v", 200, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsOK) GetPayload() *models.SkillGroupMemberDivisionList {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SkillGroupMemberDivisionList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsBadRequest creates a GetRoutingSkillgroupMembersDivisionsBadRequest with default headers values
func NewGetRoutingSkillgroupMembersDivisionsBadRequest() *GetRoutingSkillgroupMembersDivisionsBadRequest {
	return &GetRoutingSkillgroupMembersDivisionsBadRequest{}
}

/*
GetRoutingSkillgroupMembersDivisionsBadRequest describes a response with status code 400, with default header values.

The request could not be understood by the server due to malformed syntax.
*/
type GetRoutingSkillgroupMembersDivisionsBadRequest struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions bad request response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions bad request response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions bad request response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions bad request response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions bad request response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsBadRequest  %+v", 400, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsBadRequest  %+v", 400, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsUnauthorized creates a GetRoutingSkillgroupMembersDivisionsUnauthorized with default headers values
func NewGetRoutingSkillgroupMembersDivisionsUnauthorized() *GetRoutingSkillgroupMembersDivisionsUnauthorized {
	return &GetRoutingSkillgroupMembersDivisionsUnauthorized{}
}

/*
GetRoutingSkillgroupMembersDivisionsUnauthorized describes a response with status code 401, with default header values.

No authentication bearer token specified in authorization header.
*/
type GetRoutingSkillgroupMembersDivisionsUnauthorized struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions unauthorized response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions unauthorized response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions unauthorized response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions unauthorized response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions unauthorized response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsForbidden creates a GetRoutingSkillgroupMembersDivisionsForbidden with default headers values
func NewGetRoutingSkillgroupMembersDivisionsForbidden() *GetRoutingSkillgroupMembersDivisionsForbidden {
	return &GetRoutingSkillgroupMembersDivisionsForbidden{}
}

/*
GetRoutingSkillgroupMembersDivisionsForbidden describes a response with status code 403, with default header values.

You are not authorized to perform the requested action.
*/
type GetRoutingSkillgroupMembersDivisionsForbidden struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions forbidden response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions forbidden response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions forbidden response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions forbidden response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions forbidden response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetRoutingSkillgroupMembersDivisionsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsForbidden  %+v", 403, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsForbidden) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsForbidden  %+v", 403, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsForbidden) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsNotFound creates a GetRoutingSkillgroupMembersDivisionsNotFound with default headers values
func NewGetRoutingSkillgroupMembersDivisionsNotFound() *GetRoutingSkillgroupMembersDivisionsNotFound {
	return &GetRoutingSkillgroupMembersDivisionsNotFound{}
}

/*
GetRoutingSkillgroupMembersDivisionsNotFound describes a response with status code 404, with default header values.

The requested resource was not found.
*/
type GetRoutingSkillgroupMembersDivisionsNotFound struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions not found response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions not found response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions not found response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions not found response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions not found response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetRoutingSkillgroupMembersDivisionsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsNotFound  %+v", 404, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsNotFound  %+v", 404, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsRequestTimeout creates a GetRoutingSkillgroupMembersDivisionsRequestTimeout with default headers values
func NewGetRoutingSkillgroupMembersDivisionsRequestTimeout() *GetRoutingSkillgroupMembersDivisionsRequestTimeout {
	return &GetRoutingSkillgroupMembersDivisionsRequestTimeout{}
}

/*
GetRoutingSkillgroupMembersDivisionsRequestTimeout describes a response with status code 408, with default header values.

The client did not produce a request within the server timeout limit. This can be caused by a slow network connection and/or large payloads.
*/
type GetRoutingSkillgroupMembersDivisionsRequestTimeout struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions request timeout response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions request timeout response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions request timeout response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions request timeout response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions request timeout response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) IsCode(code int) bool {
	return code == 408
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsRequestTimeout  %+v", 408, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsRequestTimeout  %+v", 408, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge creates a GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge with default headers values
func NewGetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge() *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge {
	return &GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge{}
}

/*
GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge describes a response with status code 413, with default header values.

The request is over the size limit. Content-Length: %s, Maximum bytes: %s
*/
type GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions request entity too large response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions request entity too large response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions request entity too large response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions request entity too large response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions request entity too large response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) IsCode(code int) bool {
	return code == 413
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsUnsupportedMediaType creates a GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType with default headers values
func NewGetRoutingSkillgroupMembersDivisionsUnsupportedMediaType() *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType {
	return &GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType{}
}

/*
GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType describes a response with status code 415, with default header values.

Unsupported Media Type - Unsupported or incorrect media type, such as an incorrect Content-Type value in the header.
*/
type GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions unsupported media type response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions unsupported media type response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions unsupported media type response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions unsupported media type response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions unsupported media type response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsTooManyRequests creates a GetRoutingSkillgroupMembersDivisionsTooManyRequests with default headers values
func NewGetRoutingSkillgroupMembersDivisionsTooManyRequests() *GetRoutingSkillgroupMembersDivisionsTooManyRequests {
	return &GetRoutingSkillgroupMembersDivisionsTooManyRequests{}
}

/*
GetRoutingSkillgroupMembersDivisionsTooManyRequests describes a response with status code 429, with default header values.

Rate limit exceeded the maximum. Retry the request in [%s] seconds
*/
type GetRoutingSkillgroupMembersDivisionsTooManyRequests struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions too many requests response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions too many requests response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions too many requests response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get routing skillgroup members divisions too many requests response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get routing skillgroup members divisions too many requests response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsInternalServerError creates a GetRoutingSkillgroupMembersDivisionsInternalServerError with default headers values
func NewGetRoutingSkillgroupMembersDivisionsInternalServerError() *GetRoutingSkillgroupMembersDivisionsInternalServerError {
	return &GetRoutingSkillgroupMembersDivisionsInternalServerError{}
}

/*
GetRoutingSkillgroupMembersDivisionsInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition which prevented it from fulfilling the request.
*/
type GetRoutingSkillgroupMembersDivisionsInternalServerError struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions internal server error response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions internal server error response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions internal server error response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get routing skillgroup members divisions internal server error response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get routing skillgroup members divisions internal server error response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsServiceUnavailable creates a GetRoutingSkillgroupMembersDivisionsServiceUnavailable with default headers values
func NewGetRoutingSkillgroupMembersDivisionsServiceUnavailable() *GetRoutingSkillgroupMembersDivisionsServiceUnavailable {
	return &GetRoutingSkillgroupMembersDivisionsServiceUnavailable{}
}

/*
GetRoutingSkillgroupMembersDivisionsServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable - The server is currently unavailable (because it is overloaded or down for maintenance).
*/
type GetRoutingSkillgroupMembersDivisionsServiceUnavailable struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions service unavailable response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions service unavailable response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions service unavailable response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get routing skillgroup members divisions service unavailable response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get routing skillgroup members divisions service unavailable response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutingSkillgroupMembersDivisionsGatewayTimeout creates a GetRoutingSkillgroupMembersDivisionsGatewayTimeout with default headers values
func NewGetRoutingSkillgroupMembersDivisionsGatewayTimeout() *GetRoutingSkillgroupMembersDivisionsGatewayTimeout {
	return &GetRoutingSkillgroupMembersDivisionsGatewayTimeout{}
}

/*
GetRoutingSkillgroupMembersDivisionsGatewayTimeout describes a response with status code 504, with default header values.

The request timed out.
*/
type GetRoutingSkillgroupMembersDivisionsGatewayTimeout struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get routing skillgroup members divisions gateway timeout response has a 2xx status code
func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get routing skillgroup members divisions gateway timeout response has a 3xx status code
func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get routing skillgroup members divisions gateway timeout response has a 4xx status code
func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get routing skillgroup members divisions gateway timeout response has a 5xx status code
func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get routing skillgroup members divisions gateway timeout response a status code equal to that given
func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /api/v2/routing/skillgroups/{skillGroupId}/members/divisions][%d] getRoutingSkillgroupMembersDivisionsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetRoutingSkillgroupMembersDivisionsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
