// Code generated by go-swagger; DO NOT EDIT.

package coaching

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCoachingAppointmentParams creates a new GetCoachingAppointmentParams object
// with the default values initialized.
func NewGetCoachingAppointmentParams() *GetCoachingAppointmentParams {
	var ()
	return &GetCoachingAppointmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCoachingAppointmentParamsWithTimeout creates a new GetCoachingAppointmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCoachingAppointmentParamsWithTimeout(timeout time.Duration) *GetCoachingAppointmentParams {
	var ()
	return &GetCoachingAppointmentParams{

		timeout: timeout,
	}
}

// NewGetCoachingAppointmentParamsWithContext creates a new GetCoachingAppointmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCoachingAppointmentParamsWithContext(ctx context.Context) *GetCoachingAppointmentParams {
	var ()
	return &GetCoachingAppointmentParams{

		Context: ctx,
	}
}

// NewGetCoachingAppointmentParamsWithHTTPClient creates a new GetCoachingAppointmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCoachingAppointmentParamsWithHTTPClient(client *http.Client) *GetCoachingAppointmentParams {
	var ()
	return &GetCoachingAppointmentParams{
		HTTPClient: client,
	}
}

/*GetCoachingAppointmentParams contains all the parameters to send to the API endpoint
for the get coaching appointment operation typically these are written to a http.Request
*/
type GetCoachingAppointmentParams struct {

	/*AppointmentID
	  The ID of the coaching appointment.

	*/
	AppointmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get coaching appointment params
func (o *GetCoachingAppointmentParams) WithTimeout(timeout time.Duration) *GetCoachingAppointmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get coaching appointment params
func (o *GetCoachingAppointmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get coaching appointment params
func (o *GetCoachingAppointmentParams) WithContext(ctx context.Context) *GetCoachingAppointmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get coaching appointment params
func (o *GetCoachingAppointmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get coaching appointment params
func (o *GetCoachingAppointmentParams) WithHTTPClient(client *http.Client) *GetCoachingAppointmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get coaching appointment params
func (o *GetCoachingAppointmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppointmentID adds the appointmentID to the get coaching appointment params
func (o *GetCoachingAppointmentParams) WithAppointmentID(appointmentID string) *GetCoachingAppointmentParams {
	o.SetAppointmentID(appointmentID)
	return o
}

// SetAppointmentID adds the appointmentId to the get coaching appointment params
func (o *GetCoachingAppointmentParams) SetAppointmentID(appointmentID string) {
	o.AppointmentID = appointmentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCoachingAppointmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appointmentId
	if err := r.SetPathParam("appointmentId", o.AppointmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
