// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIntegrationsBotconnectorIntegrationIDBotParams creates a new GetIntegrationsBotconnectorIntegrationIDBotParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIntegrationsBotconnectorIntegrationIDBotParams() *GetIntegrationsBotconnectorIntegrationIDBotParams {
	return &GetIntegrationsBotconnectorIntegrationIDBotParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithTimeout creates a new GetIntegrationsBotconnectorIntegrationIDBotParams object
// with the ability to set a timeout on a request.
func NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithTimeout(timeout time.Duration) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	return &GetIntegrationsBotconnectorIntegrationIDBotParams{
		timeout: timeout,
	}
}

// NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithContext creates a new GetIntegrationsBotconnectorIntegrationIDBotParams object
// with the ability to set a context for a request.
func NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithContext(ctx context.Context) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	return &GetIntegrationsBotconnectorIntegrationIDBotParams{
		Context: ctx,
	}
}

// NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithHTTPClient creates a new GetIntegrationsBotconnectorIntegrationIDBotParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIntegrationsBotconnectorIntegrationIDBotParamsWithHTTPClient(client *http.Client) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	return &GetIntegrationsBotconnectorIntegrationIDBotParams{
		HTTPClient: client,
	}
}

/*
GetIntegrationsBotconnectorIntegrationIDBotParams contains all the parameters to send to the API endpoint

	for the get integrations botconnector integration Id bot operation.

	Typically these are written to a http.Request.
*/
type GetIntegrationsBotconnectorIntegrationIDBotParams struct {

	/* BotID.

	   The botID for this bot
	*/
	BotID string

	/* IntegrationID.

	   The integration ID for this group of bots
	*/
	IntegrationID string

	/* Version.

	   Specific Version
	*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get integrations botconnector integration Id bot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithDefaults() *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get integrations botconnector integration Id bot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithTimeout(timeout time.Duration) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithContext(ctx context.Context) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithHTTPClient(client *http.Client) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBotID adds the botID to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithBotID(botID string) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetBotID(botID)
	return o
}

// SetBotID adds the botId to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetBotID(botID string) {
	o.BotID = botID
}

// WithIntegrationID adds the integrationID to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithIntegrationID(integrationID string) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetIntegrationID(integrationID string) {
	o.IntegrationID = integrationID
}

// WithVersion adds the version to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WithVersion(version *string) *GetIntegrationsBotconnectorIntegrationIDBotParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get integrations botconnector integration Id bot params
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntegrationsBotconnectorIntegrationIDBotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param botId
	if err := r.SetPathParam("botId", o.BotID); err != nil {
		return err
	}

	// path param integrationId
	if err := r.SetPathParam("integrationId", o.IntegrationID); err != nil {
		return err
	}

	if o.Version != nil {

		// query param version
		var qrVersion string

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
