// Code generated by go-swagger; DO NOT EDIT.

package gamification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/freman/genesysapi/models"
)

// GetGamificationScorecardsProfileMetricUsersValuesTrendsReader is a Reader for the GetGamificationScorecardsProfileMetricUsersValuesTrends structure.
type GetGamificationScorecardsProfileMetricUsersValuesTrendsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsOK creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsOK with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsOK() *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsOK{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsOK struct {
	Payload *models.MetricValueTrendAverage
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends o k response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends o k response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends o k response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends o k response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends o k response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsOK  %+v", 200, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsOK  %+v", 200, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) GetPayload() *models.MetricValueTrendAverage {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetricValueTrendAverage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest() *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest describes a response with status code 400, with default header values.

The request could not be understood by the server due to malformed syntax.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends bad request response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends bad request response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends bad request response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends bad request response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends bad request response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest  %+v", 400, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest  %+v", 400, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized() *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized describes a response with status code 401, with default header values.

No authentication bearer token specified in authorization header.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends unauthorized response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends unauthorized response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends unauthorized response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends unauthorized response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends unauthorized response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden() *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden describes a response with status code 403, with default header values.

You are not authorized to perform the requested action.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends forbidden response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends forbidden response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends forbidden response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends forbidden response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends forbidden response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsForbidden  %+v", 403, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsForbidden  %+v", 403, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound() *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound describes a response with status code 404, with default header values.

The requested resource was not found.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends not found response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends not found response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends not found response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends not found response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends not found response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsNotFound  %+v", 404, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsNotFound  %+v", 404, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout() *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout describes a response with status code 408, with default header values.

The client did not produce a request within the server timeout limit. This can be caused by a slow network connection and/or large payloads.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends request timeout response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends request timeout response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends request timeout response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends request timeout response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends request timeout response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) IsCode(code int) bool {
	return code == 408
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout  %+v", 408, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout  %+v", 408, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge() *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge describes a response with status code 413, with default header values.

The request is over the size limit. Maximum bytes: %s
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends request entity too large response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends request entity too large response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends request entity too large response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends request entity too large response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends request entity too large response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) IsCode(code int) bool {
	return code == 413
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType() *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType describes a response with status code 415, with default header values.

Unsupported Media Type - Unsupported or incorrect media type, such as an incorrect Content-Type value in the header.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends unsupported media type response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends unsupported media type response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends unsupported media type response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends unsupported media type response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends unsupported media type response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests() *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests describes a response with status code 429, with default header values.

Rate limit exceeded the maximum. Retry the request in [%s] seconds
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends too many requests response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends too many requests response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends too many requests response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends too many requests response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get gamification scorecards profile metric users values trends too many requests response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError() *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError describes a response with status code 500, with default header values.

The server encountered an unexpected condition which prevented it from fulfilling the request.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends internal server error response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends internal server error response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends internal server error response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends internal server error response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get gamification scorecards profile metric users values trends internal server error response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable() *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable - The server is currently unavailable (because it is overloaded or down for maintenance).
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends service unavailable response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends service unavailable response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends service unavailable response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends service unavailable response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get gamification scorecards profile metric users values trends service unavailable response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout creates a GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout with default headers values
func NewGetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout() *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout {
	return &GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout{}
}

/*
GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout describes a response with status code 504, with default header values.

The request timed out.
*/
type GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get gamification scorecards profile metric users values trends gateway timeout response has a 2xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gamification scorecards profile metric users values trends gateway timeout response has a 3xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gamification scorecards profile metric users values trends gateway timeout response has a 4xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gamification scorecards profile metric users values trends gateway timeout response has a 5xx status code
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get gamification scorecards profile metric users values trends gateway timeout response a status code equal to that given
func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /api/v2/gamification/scorecards/profiles/{profileId}/metrics/{metricId}/users/values/trends][%d] getGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetGamificationScorecardsProfileMetricUsersValuesTrendsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
