// Code generated by go-swagger; DO NOT EDIT.

package conversations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConversationSecureattributesParams creates a new GetConversationSecureattributesParams object
// with the default values initialized.
func NewGetConversationSecureattributesParams() *GetConversationSecureattributesParams {
	var ()
	return &GetConversationSecureattributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConversationSecureattributesParamsWithTimeout creates a new GetConversationSecureattributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConversationSecureattributesParamsWithTimeout(timeout time.Duration) *GetConversationSecureattributesParams {
	var ()
	return &GetConversationSecureattributesParams{

		timeout: timeout,
	}
}

// NewGetConversationSecureattributesParamsWithContext creates a new GetConversationSecureattributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConversationSecureattributesParamsWithContext(ctx context.Context) *GetConversationSecureattributesParams {
	var ()
	return &GetConversationSecureattributesParams{

		Context: ctx,
	}
}

// NewGetConversationSecureattributesParamsWithHTTPClient creates a new GetConversationSecureattributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConversationSecureattributesParamsWithHTTPClient(client *http.Client) *GetConversationSecureattributesParams {
	var ()
	return &GetConversationSecureattributesParams{
		HTTPClient: client,
	}
}

/*GetConversationSecureattributesParams contains all the parameters to send to the API endpoint
for the get conversation secureattributes operation typically these are written to a http.Request
*/
type GetConversationSecureattributesParams struct {

	/*ConversationID
	  conversation ID

	*/
	ConversationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) WithTimeout(timeout time.Duration) *GetConversationSecureattributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) WithContext(ctx context.Context) *GetConversationSecureattributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) WithHTTPClient(client *http.Client) *GetConversationSecureattributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConversationID adds the conversationID to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) WithConversationID(conversationID string) *GetConversationSecureattributesParams {
	o.SetConversationID(conversationID)
	return o
}

// SetConversationID adds the conversationId to the get conversation secureattributes params
func (o *GetConversationSecureattributesParams) SetConversationID(conversationID string) {
	o.ConversationID = conversationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetConversationSecureattributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param conversationId
	if err := r.SetPathParam("conversationId", o.ConversationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
