// Code generated by go-swagger; DO NOT EDIT.

package conversations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConversationsCallParticipantWrapupcodesParams creates a new GetConversationsCallParticipantWrapupcodesParams object
// with the default values initialized.
func NewGetConversationsCallParticipantWrapupcodesParams() *GetConversationsCallParticipantWrapupcodesParams {
	var ()
	return &GetConversationsCallParticipantWrapupcodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConversationsCallParticipantWrapupcodesParamsWithTimeout creates a new GetConversationsCallParticipantWrapupcodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConversationsCallParticipantWrapupcodesParamsWithTimeout(timeout time.Duration) *GetConversationsCallParticipantWrapupcodesParams {
	var ()
	return &GetConversationsCallParticipantWrapupcodesParams{

		timeout: timeout,
	}
}

// NewGetConversationsCallParticipantWrapupcodesParamsWithContext creates a new GetConversationsCallParticipantWrapupcodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConversationsCallParticipantWrapupcodesParamsWithContext(ctx context.Context) *GetConversationsCallParticipantWrapupcodesParams {
	var ()
	return &GetConversationsCallParticipantWrapupcodesParams{

		Context: ctx,
	}
}

// NewGetConversationsCallParticipantWrapupcodesParamsWithHTTPClient creates a new GetConversationsCallParticipantWrapupcodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConversationsCallParticipantWrapupcodesParamsWithHTTPClient(client *http.Client) *GetConversationsCallParticipantWrapupcodesParams {
	var ()
	return &GetConversationsCallParticipantWrapupcodesParams{
		HTTPClient: client,
	}
}

/*GetConversationsCallParticipantWrapupcodesParams contains all the parameters to send to the API endpoint
for the get conversations call participant wrapupcodes operation typically these are written to a http.Request
*/
type GetConversationsCallParticipantWrapupcodesParams struct {

	/*ConversationID
	  conversationId

	*/
	ConversationID string
	/*ParticipantID
	  participantId

	*/
	ParticipantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) WithTimeout(timeout time.Duration) *GetConversationsCallParticipantWrapupcodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) WithContext(ctx context.Context) *GetConversationsCallParticipantWrapupcodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) WithHTTPClient(client *http.Client) *GetConversationsCallParticipantWrapupcodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConversationID adds the conversationID to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) WithConversationID(conversationID string) *GetConversationsCallParticipantWrapupcodesParams {
	o.SetConversationID(conversationID)
	return o
}

// SetConversationID adds the conversationId to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) SetConversationID(conversationID string) {
	o.ConversationID = conversationID
}

// WithParticipantID adds the participantID to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) WithParticipantID(participantID string) *GetConversationsCallParticipantWrapupcodesParams {
	o.SetParticipantID(participantID)
	return o
}

// SetParticipantID adds the participantId to the get conversations call participant wrapupcodes params
func (o *GetConversationsCallParticipantWrapupcodesParams) SetParticipantID(participantID string) {
	o.ParticipantID = participantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetConversationsCallParticipantWrapupcodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param conversationId
	if err := r.SetPathParam("conversationId", o.ConversationID); err != nil {
		return err
	}

	// path param participantId
	if err := r.SetPathParam("participantId", o.ParticipantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
