// Code generated by go-swagger; DO NOT EDIT.

package conversations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/freman/genesysapi/models"
)

// NewPatchConversationsChatParticipantAttributesParams creates a new PatchConversationsChatParticipantAttributesParams object
// with the default values initialized.
func NewPatchConversationsChatParticipantAttributesParams() *PatchConversationsChatParticipantAttributesParams {
	var ()
	return &PatchConversationsChatParticipantAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchConversationsChatParticipantAttributesParamsWithTimeout creates a new PatchConversationsChatParticipantAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchConversationsChatParticipantAttributesParamsWithTimeout(timeout time.Duration) *PatchConversationsChatParticipantAttributesParams {
	var ()
	return &PatchConversationsChatParticipantAttributesParams{

		timeout: timeout,
	}
}

// NewPatchConversationsChatParticipantAttributesParamsWithContext creates a new PatchConversationsChatParticipantAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchConversationsChatParticipantAttributesParamsWithContext(ctx context.Context) *PatchConversationsChatParticipantAttributesParams {
	var ()
	return &PatchConversationsChatParticipantAttributesParams{

		Context: ctx,
	}
}

// NewPatchConversationsChatParticipantAttributesParamsWithHTTPClient creates a new PatchConversationsChatParticipantAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchConversationsChatParticipantAttributesParamsWithHTTPClient(client *http.Client) *PatchConversationsChatParticipantAttributesParams {
	var ()
	return &PatchConversationsChatParticipantAttributesParams{
		HTTPClient: client,
	}
}

/*PatchConversationsChatParticipantAttributesParams contains all the parameters to send to the API endpoint
for the patch conversations chat participant attributes operation typically these are written to a http.Request
*/
type PatchConversationsChatParticipantAttributesParams struct {

	/*Body
	  Participant attributes

	*/
	Body *models.ParticipantAttributes
	/*ConversationID
	  conversationId

	*/
	ConversationID string
	/*ParticipantID
	  participantId

	*/
	ParticipantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithTimeout(timeout time.Duration) *PatchConversationsChatParticipantAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithContext(ctx context.Context) *PatchConversationsChatParticipantAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithHTTPClient(client *http.Client) *PatchConversationsChatParticipantAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithBody(body *models.ParticipantAttributes) *PatchConversationsChatParticipantAttributesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetBody(body *models.ParticipantAttributes) {
	o.Body = body
}

// WithConversationID adds the conversationID to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithConversationID(conversationID string) *PatchConversationsChatParticipantAttributesParams {
	o.SetConversationID(conversationID)
	return o
}

// SetConversationID adds the conversationId to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetConversationID(conversationID string) {
	o.ConversationID = conversationID
}

// WithParticipantID adds the participantID to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) WithParticipantID(participantID string) *PatchConversationsChatParticipantAttributesParams {
	o.SetParticipantID(participantID)
	return o
}

// SetParticipantID adds the participantId to the patch conversations chat participant attributes params
func (o *PatchConversationsChatParticipantAttributesParams) SetParticipantID(participantID string) {
	o.ParticipantID = participantID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchConversationsChatParticipantAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param conversationId
	if err := r.SetPathParam("conversationId", o.ConversationID); err != nil {
		return err
	}

	// path param participantId
	if err := r.SetPathParam("participantId", o.ParticipantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
