// Code generated by go-swagger; DO NOT EDIT.

package outbound

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteOutboundDnclistEmailaddressesParams creates a new DeleteOutboundDnclistEmailaddressesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOutboundDnclistEmailaddressesParams() *DeleteOutboundDnclistEmailaddressesParams {
	return &DeleteOutboundDnclistEmailaddressesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOutboundDnclistEmailaddressesParamsWithTimeout creates a new DeleteOutboundDnclistEmailaddressesParams object
// with the ability to set a timeout on a request.
func NewDeleteOutboundDnclistEmailaddressesParamsWithTimeout(timeout time.Duration) *DeleteOutboundDnclistEmailaddressesParams {
	return &DeleteOutboundDnclistEmailaddressesParams{
		timeout: timeout,
	}
}

// NewDeleteOutboundDnclistEmailaddressesParamsWithContext creates a new DeleteOutboundDnclistEmailaddressesParams object
// with the ability to set a context for a request.
func NewDeleteOutboundDnclistEmailaddressesParamsWithContext(ctx context.Context) *DeleteOutboundDnclistEmailaddressesParams {
	return &DeleteOutboundDnclistEmailaddressesParams{
		Context: ctx,
	}
}

// NewDeleteOutboundDnclistEmailaddressesParamsWithHTTPClient creates a new DeleteOutboundDnclistEmailaddressesParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOutboundDnclistEmailaddressesParamsWithHTTPClient(client *http.Client) *DeleteOutboundDnclistEmailaddressesParams {
	return &DeleteOutboundDnclistEmailaddressesParams{
		HTTPClient: client,
	}
}

/*
DeleteOutboundDnclistEmailaddressesParams contains all the parameters to send to the API endpoint

	for the delete outbound dnclist emailaddresses operation.

	Typically these are written to a http.Request.
*/
type DeleteOutboundDnclistEmailaddressesParams struct {

	/* DncListID.

	   DncList ID
	*/
	DncListID string

	/* ExpiredOnly.

	   Set to true to only remove DNC entries that are expired
	*/
	ExpiredOnly *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete outbound dnclist emailaddresses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOutboundDnclistEmailaddressesParams) WithDefaults() *DeleteOutboundDnclistEmailaddressesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete outbound dnclist emailaddresses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOutboundDnclistEmailaddressesParams) SetDefaults() {
	var (
		expiredOnlyDefault = bool(false)
	)

	val := DeleteOutboundDnclistEmailaddressesParams{
		ExpiredOnly: &expiredOnlyDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) WithTimeout(timeout time.Duration) *DeleteOutboundDnclistEmailaddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) WithContext(ctx context.Context) *DeleteOutboundDnclistEmailaddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) WithHTTPClient(client *http.Client) *DeleteOutboundDnclistEmailaddressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDncListID adds the dncListID to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) WithDncListID(dncListID string) *DeleteOutboundDnclistEmailaddressesParams {
	o.SetDncListID(dncListID)
	return o
}

// SetDncListID adds the dncListId to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) SetDncListID(dncListID string) {
	o.DncListID = dncListID
}

// WithExpiredOnly adds the expiredOnly to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) WithExpiredOnly(expiredOnly *bool) *DeleteOutboundDnclistEmailaddressesParams {
	o.SetExpiredOnly(expiredOnly)
	return o
}

// SetExpiredOnly adds the expiredOnly to the delete outbound dnclist emailaddresses params
func (o *DeleteOutboundDnclistEmailaddressesParams) SetExpiredOnly(expiredOnly *bool) {
	o.ExpiredOnly = expiredOnly
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOutboundDnclistEmailaddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dncListId
	if err := r.SetPathParam("dncListId", o.DncListID); err != nil {
		return err
	}

	if o.ExpiredOnly != nil {

		// query param expiredOnly
		var qrExpiredOnly bool

		if o.ExpiredOnly != nil {
			qrExpiredOnly = *o.ExpiredOnly
		}
		qExpiredOnly := swag.FormatBool(qrExpiredOnly)
		if qExpiredOnly != "" {

			if err := r.SetQueryParam("expiredOnly", qExpiredOnly); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
