// Code generated by go-swagger; DO NOT EDIT.

package language_understanding

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/freman/genesysapi/models"
)

// NewPostLanguageunderstandingDomainVersionDetectParams creates a new PostLanguageunderstandingDomainVersionDetectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostLanguageunderstandingDomainVersionDetectParams() *PostLanguageunderstandingDomainVersionDetectParams {
	return &PostLanguageunderstandingDomainVersionDetectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostLanguageunderstandingDomainVersionDetectParamsWithTimeout creates a new PostLanguageunderstandingDomainVersionDetectParams object
// with the ability to set a timeout on a request.
func NewPostLanguageunderstandingDomainVersionDetectParamsWithTimeout(timeout time.Duration) *PostLanguageunderstandingDomainVersionDetectParams {
	return &PostLanguageunderstandingDomainVersionDetectParams{
		timeout: timeout,
	}
}

// NewPostLanguageunderstandingDomainVersionDetectParamsWithContext creates a new PostLanguageunderstandingDomainVersionDetectParams object
// with the ability to set a context for a request.
func NewPostLanguageunderstandingDomainVersionDetectParamsWithContext(ctx context.Context) *PostLanguageunderstandingDomainVersionDetectParams {
	return &PostLanguageunderstandingDomainVersionDetectParams{
		Context: ctx,
	}
}

// NewPostLanguageunderstandingDomainVersionDetectParamsWithHTTPClient creates a new PostLanguageunderstandingDomainVersionDetectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostLanguageunderstandingDomainVersionDetectParamsWithHTTPClient(client *http.Client) *PostLanguageunderstandingDomainVersionDetectParams {
	return &PostLanguageunderstandingDomainVersionDetectParams{
		HTTPClient: client,
	}
}

/*
PostLanguageunderstandingDomainVersionDetectParams contains all the parameters to send to the API endpoint

	for the post languageunderstanding domain version detect operation.

	Typically these are written to a http.Request.
*/
type PostLanguageunderstandingDomainVersionDetectParams struct {

	/* Body.

	   The input data to perform detection on.
	*/
	Body *models.NluDetectionRequest

	/* DomainID.

	   ID of the NLU domain.
	*/
	DomainID string

	/* DomainVersionID.

	   ID of the NLU domain version.
	*/
	DomainVersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post languageunderstanding domain version detect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithDefaults() *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post languageunderstanding domain version detect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithTimeout(timeout time.Duration) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithContext(ctx context.Context) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithHTTPClient(client *http.Client) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithBody(body *models.NluDetectionRequest) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetBody(body *models.NluDetectionRequest) {
	o.Body = body
}

// WithDomainID adds the domainID to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithDomainID(domainID string) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetDomainID(domainID string) {
	o.DomainID = domainID
}

// WithDomainVersionID adds the domainVersionID to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) WithDomainVersionID(domainVersionID string) *PostLanguageunderstandingDomainVersionDetectParams {
	o.SetDomainVersionID(domainVersionID)
	return o
}

// SetDomainVersionID adds the domainVersionId to the post languageunderstanding domain version detect params
func (o *PostLanguageunderstandingDomainVersionDetectParams) SetDomainVersionID(domainVersionID string) {
	o.DomainVersionID = domainVersionID
}

// WriteToRequest writes these params to a swagger request
func (o *PostLanguageunderstandingDomainVersionDetectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param domainId
	if err := r.SetPathParam("domainId", o.DomainID); err != nil {
		return err
	}

	// path param domainVersionId
	if err := r.SetPathParam("domainVersionId", o.DomainVersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
