// Code generated by go-swagger; DO NOT EDIT.

package workforce_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/freman/genesysapi/models"
)

// PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryReader is a Reader for the PostWorkforcemanagementManagementunitTimeofflimitsValuesQuery structure.
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK handles this case with default header values.

successful operation
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK struct {
	Payload *models.QueryTimeOffLimitValuesResponse
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK  %+v", 200, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK) GetPayload() *models.QueryTimeOffLimitValuesResponse {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QueryTimeOffLimitValuesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest handles this case with default header values.

The request could not be understood by the server due to malformed syntax.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest  %+v", 400, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized handles this case with default header values.

No authentication bearer token specified in authorization header.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized  %+v", 401, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden handles this case with default header values.

You are not authorized to perform the requested action.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden  %+v", 403, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound handles this case with default header values.

The requested resource was not found.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound  %+v", 404, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout handles this case with default header values.

The client did not produce a request within the server timeout limit. This can be caused by a slow network connection and/or large payloads.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout  %+v", 408, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge handles this case with default header values.

The request is over the size limit. Content-Length: %s
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType handles this case with default header values.

Unsupported Media Type - Unsupported or incorrect media type, such as an incorrect Content-Type value in the header.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests handles this case with default header values.

Rate limit exceeded the maximum. Retry the request in [%s] seconds
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests  %+v", 429, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError handles this case with default header values.

The server encountered an unexpected condition which prevented it from fulfilling the request.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError  %+v", 500, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable handles this case with default header values.

Service Unavailable - The server is currently unavailable (because it is overloaded or down for maintenance).
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable  %+v", 503, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout creates a PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout with default headers values
func NewPostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout() *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout {
	return &PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout{}
}

/*PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout handles this case with default header values.

The request timed out.
*/
type PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout struct {
	Payload *models.ErrorBody
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout) Error() string {
	return fmt.Sprintf("[POST /api/v2/workforcemanagement/managementunits/{managementUnitId}/timeofflimits/values/query][%d] postWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout  %+v", 504, o.Payload)
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *PostWorkforcemanagementManagementunitTimeofflimitsValuesQueryGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
