// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContactCenterSettings contact center settings
//
// swagger:model ContactCenterSettings
type ContactCenterSettings struct {

	// Strip skills from transfer
	RemoveSkillsFromBlindTransfer bool `json:"removeSkillsFromBlindTransfer,omitempty"`
}

// Validate validates this contact center settings
func (m *ContactCenterSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContactCenterSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContactCenterSettings) UnmarshalBinary(b []byte) error {
	var res ContactCenterSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
