// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TextBotFlowLaunchResponse Information related to a successful launch of a bot flow. The ID will be used in subsequent turn requests of the bot flow.
//
// swagger:model TextBotFlowLaunchResponse
type TextBotFlowLaunchResponse struct {

	// The session ID of the bot flow, used to send to subsequent turn requests
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this text bot flow launch response
func (m *TextBotFlowLaunchResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TextBotFlowLaunchResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TextBotFlowLaunchResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TextBotFlowLaunchResponse) UnmarshalBinary(b []byte) error {
	var res TextBotFlowLaunchResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
