// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WhatsAppIntegrationRequest whats app integration request
//
// swagger:model WhatsAppIntegrationRequest
type WhatsAppIntegrationRequest struct {

	// The globally unique identifier for the object.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The name of the WhatsApp Integration
	// Required: true
	Name *string `json:"name"`

	// The phone number associated to the whatsApp integration
	// Required: true
	PhoneNumber *string `json:"phoneNumber"`

	// The URI for this object
	// Read Only: true
	// Format: uri
	SelfURI strfmt.URI `json:"selfUri,omitempty"`

	// The waba(WhatsApp Business Manager) certificate associated to the WhatsApp integration phone number
	// Required: true
	WabaCertificate *string `json:"wabaCertificate"`
}

// Validate validates this whats app integration request
func (m *WhatsAppIntegrationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhoneNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelfURI(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWabaCertificate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WhatsAppIntegrationRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *WhatsAppIntegrationRequest) validatePhoneNumber(formats strfmt.Registry) error {

	if err := validate.Required("phoneNumber", "body", m.PhoneNumber); err != nil {
		return err
	}

	return nil
}

func (m *WhatsAppIntegrationRequest) validateSelfURI(formats strfmt.Registry) error {

	if swag.IsZero(m.SelfURI) { // not required
		return nil
	}

	if err := validate.FormatOf("selfUri", "body", "uri", m.SelfURI.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WhatsAppIntegrationRequest) validateWabaCertificate(formats strfmt.Registry) error {

	if err := validate.Required("wabaCertificate", "body", m.WabaCertificate); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WhatsAppIntegrationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WhatsAppIntegrationRequest) UnmarshalBinary(b []byte) error {
	var res WhatsAppIntegrationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
